# Generated by Django 3.2.3 on 2021-05-30 14:20

import courses.models.lecture
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_homework_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lecture.get_file_path),
        ),
    ]
